version: '3.8'

services:
  mariadb:
    image: mariadb:10.6
    container_name: mariadb
    restart: always
    environment:
      MARIADB_DATABASE: WebSearch
      MARIADB_USER: WebSearch
      MARIADB_PASSWORD: WebSearch123!
      MARIADB_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"

  backend:
    build: .
    container_name: web_backend
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/WebSearch
      SPRING_DATASOURCE_USERNAME: WebSearch
      SPRING_DATASOURCE_PASSWORD: WebSearch123!
      SEARCHENGINE_URL: http://search-engine:3001/search
      CRAWLER_URL: http://crawler:3000
      JWT_SECRET: MySuperSecretJWTKey
